[project]
name = "quicksave"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "boto3>=1.38.30",
    "pyyaml>=6.0.2",
]
