name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Set permissions needed for OIDC authentication with PyPI
    permissions:
      id-token: write  # Required for OIDC authentication with PyPI
      contents: read   # Required to checkout the repository

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        uv build

    - name: Publish to PyPI
      run: |
        uv publish
